apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o pac/k8s/net
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: dockerdclm-api
  name: dockerdclm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dockerdclm-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o pac/k8s/net
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/dclm-network: "true"
        io.kompose.service: dockerdclm-api
    spec:
      containers:
        - env:
            - name: DATABASE
            - name: DB_PORT
            - name: DB_SERVER
            - name: DB_USER
            - name: PASSWORD
          image: caz-dev/church-system
          name: dockerdclm-api
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
